// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5735030f-4c03-47ee-9c72-54bbf890d68d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Fxasr5zPe",
    "aws_user_pools_web_client_id": "4cqbsm0v45fj1la97t8890jl9a",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Users",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
